# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FEEDBACK',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('TOPIC', models.CharField(max_length=64, null=True, blank=True)),
                ('CONTENT', models.CharField(max_length=1024, null=True, blank=True)),
                ('CREATE_USER_NAME', models.CharField(max_length=64, null=True, blank=True)),
                ('CREATE_TIME', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobStatusControl',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('TIME', models.DateTimeField(null=True, verbose_name=b'\xe6\x97\xb6\xe9\x97\xb4', blank=True)),
                ('SUCCESS', models.IntegerField(default=0, null=True, blank=True)),
                ('FAILURE', models.IntegerField(default=0, null=True, blank=True)),
                ('REVOKED', models.IntegerField(default=0, null=True, blank=True)),
                ('STARTED', models.IntegerField(default=0, null=True, blank=True)),
                ('TOTAL_JOBS', models.IntegerField(default=0, null=True, blank=True)),
                ('OWNER_ID', models.IntegerField(null=True, blank=True)),
                ('OWNER_NAME', models.CharField(max_length=128, null=True, blank=True)),
                ('OWNER_PROJECT_ID', models.IntegerField(null=True, blank=True)),
                ('OWNER_ALL', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='operation_record',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('NAME', models.CharField(max_length=64, null=True, blank=True)),
                ('PERMISSION_NAME', models.CharField(max_length=128, null=True, blank=True)),
                ('URL', models.CharField(max_length=512, null=True, blank=True)),
                ('REQUEST', models.CharField(max_length=1024, null=True, blank=True)),
                ('REQUEST_BODY', models.TextField(null=True, blank=True)),
                ('RESPONSE_CONTENT', models.TextField(null=True, blank=True)),
                ('CREATE_USER_ID', models.IntegerField(null=True, blank=True)),
                ('CREATE_USER_NAME', models.CharField(max_length=64, null=True, blank=True)),
                ('CREATE_TIME', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4', null=True)),
                ('OPERATION_IP', models.CharField(max_length=64, null=True, blank=True)),
                ('OPERATION_PORT', models.CharField(max_length=64, null=True, blank=True)),
                ('OPERATION_ACCOUNT', models.CharField(max_length=64, null=True, blank=True)),
                ('OPERATION_ACTION', models.CharField(max_length=128, null=True, blank=True)),
                ('OPERATION_DESCRIPTION', models.CharField(max_length=512, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionList',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(unique=True, max_length=64)),
                ('url', models.CharField(unique=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RoleList',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(unique=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='sudo_record',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('IP', models.CharField(max_length=64, null=True, blank=True)),
                ('ACCOUNT', models.CharField(max_length=64, null=True, blank=True)),
                ('DESCRIPTION', models.CharField(max_length=512, null=True, blank=True)),
                ('PORT', models.CharField(max_length=64, null=True, blank=True)),
                ('CREATE_USER_ID', models.IntegerField(null=True, blank=True)),
                ('CREATE_USER_NAME', models.CharField(max_length=64, null=True, blank=True)),
                ('CREATE_TIME', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_COMMAND_EVENT',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('GROUP_ID', models.IntegerField(null=True, blank=True)),
                ('CREDENTIALS_ID', models.IntegerField(null=True, blank=True)),
                ('LOGFILE', models.CharField(max_length=64, null=True, blank=True)),
                ('COMMAND_NAME', models.CharField(max_length=64, null=True, blank=True)),
                ('COMMAND_VARS', models.CharField(max_length=128, null=True, blank=True)),
                ('CREATE_TIME', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4', null=True)),
                ('CREATE_USER_ID', models.IntegerField(null=True, blank=True)),
                ('CREATE_USER_NAME', models.CharField(max_length=128, null=True, blank=True)),
                ('RESULT', models.TextField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_Group',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('NAME', models.CharField(unique=True, max_length=128)),
                ('DESCRIPTION', models.CharField(max_length=256)),
                ('VARIABLES', models.CharField(max_length=512)),
                ('TOTAL_HOSTS', models.IntegerField(null=True, blank=True)),
                ('CREATE_TIME', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4', null=True)),
                ('CREATE_USER_ID', models.IntegerField(null=True, blank=True)),
                ('CREATE_USER_NAME', models.CharField(max_length=128, null=True, blank=True)),
                ('LAST_MODIFY_TIME', models.DateTimeField(auto_now=True, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4', null=True)),
                ('MODIFY_USER_ID', models.IntegerField(null=True, blank=True)),
                ('INVENTORY_ID', models.IntegerField(default=0)),
                ('HAS_INVENTORY_SOURCE', models.BooleanField(default=True)),
                ('HAS_ACTIVE_FAILURES', models.BooleanField(default=True)),
                ('HAS_EXTENRN_SOURCE', models.BooleanField(default=True)),
                ('OWNER_ID', models.IntegerField(null=True, blank=True)),
                ('OWNER_NAME', models.CharField(max_length=128, null=True, blank=True)),
                ('OWNER_PROJECT_ID', models.IntegerField(null=True, blank=True)),
                ('OWNER_ALL', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='T_GROUP_HOST_ID',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('GROUP_ID', models.ForeignKey(related_name='relations', to='app_tower.T_Group')),
            ],
        ),
        migrations.CreateModel(
            name='T_HOST',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('NAME', models.CharField(max_length=128)),
                ('DESCRIPTION', models.CharField(max_length=256)),
                ('VARIABLES', models.CharField(max_length=512)),
                ('ENABLED', models.IntegerField(null=True, blank=True)),
                ('CREATE_TIME', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4', null=True)),
                ('CREATE_USER_ID', models.IntegerField(null=True, blank=True)),
                ('CREATE_USER_NAME', models.CharField(max_length=128, null=True, blank=True)),
                ('LAST_MODIFY_TIME', models.DateTimeField(auto_now=True, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4', null=True)),
                ('MODIFY_USER_ID', models.IntegerField(null=True, blank=True)),
                ('INVENTORY_ID', models.IntegerField(default=0)),
                ('LAST_JOB_ID', models.IntegerField(null=True, blank=True)),
                ('HAS_ACTIVE_FAILURES', models.BooleanField(default=True)),
                ('HAS_EXTENRN_SOURCE', models.BooleanField(default=True)),
                ('OWNER_ID', models.IntegerField(null=True, blank=True)),
                ('OWNER_NAME', models.CharField(max_length=128, null=True, blank=True)),
                ('OWNER_PROJECT_ID', models.IntegerField(null=True, blank=True)),
                ('OWNER_ALL', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='T_JOB',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('NAME', models.CharField(max_length=128)),
                ('DESCRIPTION', models.CharField(max_length=256)),
                ('JOB_TYPE', models.CharField(max_length=32)),
                ('INVENTORY_ID', models.IntegerField(null=True, blank=True)),
                ('PROJECT_ID', models.IntegerField(null=True, blank=True)),
                ('PLAYBOOK_ID', models.IntegerField(null=True, blank=True)),
                ('PLAYBOOK_FILE', models.CharField(max_length=256)),
                ('FORKS', models.IntegerField(null=True, blank=True)),
                ('VERBOSITY', models.IntegerField(null=True, blank=True)),
                ('JOB_TAGS', models.CharField(max_length=512)),
                ('SKIP_TAGS', models.CharField(max_length=512)),
                ('EXTRA_VARIABLES', models.CharField(max_length=512)),
                ('CREATE_TIME', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4', null=True)),
                ('CREATE_USER_ID', models.IntegerField(null=True, blank=True)),
                ('CREATE_USER_NAME', models.CharField(max_length=128, null=True, blank=True)),
                ('START_TIME', models.DateTimeField(null=True, blank=True)),
                ('FINISH_TIME', models.DateTimeField(null=True, blank=True)),
                ('ELAPSED', models.IntegerField(null=True, blank=True)),
                ('RESULT_STDOUT_TEXT', models.TextField(null=True, blank=True)),
                ('JOB_CWD', models.CharField(max_length=128)),
                ('JOB_ENV', models.CharField(max_length=128)),
                ('JOB_EXPLANATION', models.CharField(max_length=128)),
                ('JOB_ARGS', models.CharField(max_length=512)),
                ('CELERY_TASK_ID', models.CharField(max_length=256)),
                ('STATUS', models.CharField(max_length=32)),
                ('LOGFILE', models.CharField(max_length=256, null=True, blank=True)),
                ('LOGCONTENT', models.TextField(null=True, blank=True)),
                ('CANCEL_FLAG', models.BooleanField(default=False)),
                ('LUNCH_TYPE', models.CharField(max_length=32)),
                ('OWNER_ID', models.IntegerField(null=True, blank=True)),
                ('OWNER_NAME', models.CharField(max_length=128, null=True, blank=True)),
                ('OWNER_PROJECT_ID', models.IntegerField(null=True, blank=True)),
                ('OWNER_ALL', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='T_JOB_EVENT',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('JOB_ID', models.IntegerField(null=True, blank=True)),
                ('HOST_NAME', models.CharField(max_length=128)),
                ('HOST_ID', models.IntegerField(null=True, blank=True)),
                ('CREATE', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4', null=True)),
                ('MODIFY', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4', null=True)),
                ('SUCCESS', models.IntegerField(null=True, blank=True)),
                ('FAILED', models.IntegerField(null=True, blank=True)),
                ('CHANGED', models.IntegerField(null=True, blank=True)),
                ('UNREACHABLE', models.IntegerField(null=True, blank=True)),
                ('SKIPPED', models.IntegerField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_JOB_TEMPLATE',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('NAME', models.CharField(unique=True, max_length=128)),
                ('DESCRIPTION', models.CharField(max_length=256)),
                ('JOB_TYPE', models.CharField(max_length=32)),
                ('PROMPT_JOB_TYPE', models.IntegerField(null=True, blank=True)),
                ('PROJECT_ID', models.IntegerField(null=True, blank=True)),
                ('PLAYBOOK_ID', models.IntegerField(null=True, blank=True)),
                ('PLAYBOOK_FILE', models.CharField(max_length=256)),
                ('FORKS', models.IntegerField(null=True, blank=True)),
                ('VERBOSITY', models.IntegerField(null=True, blank=True)),
                ('JOB_TAGS', models.CharField(max_length=512)),
                ('SKIP_TAGS', models.CharField(max_length=512)),
                ('LABELS', models.CharField(max_length=128)),
                ('PROMPT_JOB_TAGS', models.IntegerField(null=True, blank=True)),
                ('PROMPT_SKIP_TAGS', models.IntegerField(null=True, blank=True)),
                ('EXTRA_VARIABLES', models.CharField(max_length=512)),
                ('PROMT_EXTRA_VAR', models.IntegerField(null=True, blank=True)),
                ('CREATE_TIME', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4', null=True)),
                ('CREATE_USER_ID', models.IntegerField(null=True, blank=True)),
                ('CREATE_USER_NAME', models.CharField(max_length=128, null=True, blank=True)),
                ('LAST_MODIFY_TIME', models.DateTimeField(auto_now=True, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4', null=True)),
                ('MODIFY_USER_ID', models.IntegerField(null=True, blank=True)),
                ('ADMIN_ROLE_ID', models.IntegerField(null=True, blank=True)),
                ('EXECUTE_ROLE_ID', models.IntegerField(null=True, blank=True)),
                ('READ_ROLE_ID', models.IntegerField(null=True, blank=True)),
                ('INVENTORY_ID', models.IntegerField(null=True, blank=True)),
                ('OWNER_ID', models.IntegerField(null=True, blank=True)),
                ('OWNER_NAME', models.CharField(max_length=128, null=True, blank=True)),
                ('OWNER_PROJECT_ID', models.IntegerField(null=True, blank=True)),
                ('OWNER_ALL', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='T_LOGIN_CREDENTIALS',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('NAME', models.CharField(unique=True, max_length=64)),
                ('DESCRIPTION', models.CharField(max_length=128)),
                ('OWNER_ID', models.IntegerField(null=True, blank=True)),
                ('OWNER_NAME', models.CharField(max_length=128, null=True, blank=True)),
                ('OWNER_PROJECT_ID', models.IntegerField(null=True, blank=True)),
                ('OWNER_ALL', models.BooleanField(default=False)),
                ('TYPE', models.CharField(max_length=32)),
                ('LOGIN_USER', models.CharField(max_length=32)),
                ('LOGIN_PWD', models.CharField(max_length=64)),
                ('PRIVILEGE_NAME', models.CharField(max_length=32, null=True, blank=True)),
                ('PRIVILEGE_PWD', models.CharField(max_length=64, null=True, blank=True)),
                ('CREATE_USER_ID', models.IntegerField(null=True, blank=True)),
                ('CREATE_USER_NAME', models.CharField(max_length=64, null=True, blank=True)),
                ('CREATE_TIME', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4', null=True)),
                ('LAST_MODIFY_USER_ID', models.IntegerField(null=True, blank=True)),
                ('LAST_MODIFY_TIME', models.DateTimeField(auto_now=True, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_PROJECT',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('NAME', models.CharField(unique=True, max_length=128)),
                ('DESCRIPTION', models.CharField(max_length=256, null=True, blank=True)),
                ('OWNER_ID', models.IntegerField(null=True, blank=True)),
                ('OWNER_NAME', models.CharField(max_length=128, null=True, blank=True)),
                ('OWNER_PROJECT_ID', models.IntegerField(null=True, blank=True)),
                ('OWNER_ALL', models.BooleanField(default=False)),
                ('CREATE_TIME', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4', null=True)),
                ('CREATE_USER_ID', models.IntegerField(null=True, blank=True)),
                ('CREATE_USER_NAME', models.CharField(max_length=128, null=True, blank=True)),
                ('LAST_MODIFY_TIME', models.DateTimeField(auto_now=True, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4', null=True)),
                ('MODIFY_USER_ID', models.IntegerField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_PROJECT_User_ID',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('PROJECT_ID', models.ForeignKey(related_name='relations', to='app_tower.T_PROJECT')),
            ],
        ),
        migrations.CreateModel(
            name='T_RoleList_PermissionList_ID',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('PermissionList_ID', models.ForeignKey(related_name='relations', to='app_tower.PermissionList')),
                ('RoleList_ID', models.ForeignKey(related_name='relations', to='app_tower.RoleList')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(null=True, verbose_name='last login', blank=True)),
                ('username', models.CharField(unique=True, max_length=40, db_index=True)),
                ('mobile', models.CharField(max_length=512)),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4', null=True)),
                ('email', models.EmailField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('nickname', models.CharField(max_length=64, null=True)),
                ('sex', models.CharField(max_length=2, null=True)),
                ('projects', models.ManyToManyField(to='app_tower.T_PROJECT', through='app_tower.T_PROJECT_User_ID')),
                ('role', models.ForeignKey(blank=True, to='app_tower.RoleList', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='t_project_user_id',
            name='User_ID',
            field=models.ForeignKey(related_name='relations', to='app_tower.User'),
        ),
        migrations.AddField(
            model_name='t_job_template',
            name='CREDENTIAL_MACHINE_ID',
            field=models.ForeignKey(related_name='CREDENTIAL_MACHINE_ID_T_JOB_TEMPLATE', on_delete=django.db.models.deletion.PROTECT, blank=True, to='app_tower.T_LOGIN_CREDENTIALS', null=True),
        ),
        migrations.AddField(
            model_name='t_job_template',
            name='GROUP_ID',
            field=models.ForeignKey(related_name='GROUP_ID_T_JOB_TEMPLATE', on_delete=django.db.models.deletion.PROTECT, blank=True, to='app_tower.T_Group', null=True),
        ),
        migrations.AddField(
            model_name='t_job',
            name='CREDENTIAL_MACHINE_ID',
            field=models.ForeignKey(related_name='CREDENTIAL_MACHINE_ID_T_JOB', on_delete=django.db.models.deletion.PROTECT, blank=True, to='app_tower.T_LOGIN_CREDENTIALS', null=True),
        ),
        migrations.AddField(
            model_name='t_job',
            name='GROUP_ID',
            field=models.ForeignKey(related_name='GROUP_ID_T_JOB', on_delete=django.db.models.deletion.PROTECT, blank=True, to='app_tower.T_Group', null=True),
        ),
        migrations.AddField(
            model_name='t_job',
            name='TEMPLETE_ID',
            field=models.ForeignKey(related_name='TEMPLETE_ID_T_JOB', on_delete=django.db.models.deletion.PROTECT, blank=True, to='app_tower.T_JOB_TEMPLATE', null=True),
        ),
        migrations.AddField(
            model_name='t_group_host_id',
            name='HOST_ID',
            field=models.ForeignKey(related_name='relations', to='app_tower.T_HOST'),
        ),
        migrations.AddField(
            model_name='t_group',
            name='HOSTS',
            field=models.ManyToManyField(to='app_tower.T_HOST', through='app_tower.T_GROUP_HOST_ID'),
        ),
        migrations.AddField(
            model_name='sudo_record',
            name='CREDENTIALS_ID',
            field=models.ForeignKey(blank=True, to='app_tower.T_LOGIN_CREDENTIALS', null=True),
        ),
        migrations.AddField(
            model_name='rolelist',
            name='permission',
            field=models.ManyToManyField(to='app_tower.PermissionList', through='app_tower.T_RoleList_PermissionList_ID'),
        ),
    ]
